# Management Pod
apiVersion: v1
kind: Pod
metadata:
  name: test-orchestration
  labels:
    app: test-orchestration
spec:
  serviceAccountName: pod-creator
  containers:
    - name: environment
      image: ${CACTUS_ORCHESTRATOR_IMAGE}
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
      env:
        - name: TEST_EXECUTION_FQDN
          value: ${TEST_EXECUTION_FQDN}
        - name: ORCHESTRATOR_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: orchestrator-db-secret
              key: ORCHESTRATOR_DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: test-orchestration-service
spec:
  selector:
    app: test-orchestration
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32080  # Expose on host
  type: NodePort
